### ISSUE TITLE
[Graphic] Make tasks location a KeyValuePair with a Quaternion rotation + restrict which object can spawn where

### ISSUE THREAD

**Issue by orelgs** [orelgs/MTA-Final-Project#8]
Requires adding them to the ObjectSpawner Prefab in the Resources/PhotonPrefabs folder.

**Comment by orelgs** [comment]
Depends on #9 #10

**Comment by orelgs** [comment]
Each location requires a certain logical rotation.
Plus, not every interactable object can spawn on all locations.

**Comment by kesemsh** [comment]
Use the Task Locations Excel
